// Generated by gencpp from file moveit_commander/AddObjectToSceneRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENEREQUEST_H
#define MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace moveit_commander
{
template <class ContainerAllocator>
struct AddObjectToSceneRequest_
{
  typedef AddObjectToSceneRequest_<ContainerAllocator> Type;

  AddObjectToSceneRequest_()
    : name()
    , object_template()
    , frame_id()
    , pose()  {
    }
  AddObjectToSceneRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , object_template(_alloc)
    , frame_id(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_template_type;
  _object_template_type object_template;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddObjectToSceneRequest_

typedef ::moveit_commander::AddObjectToSceneRequest_<std::allocator<void> > AddObjectToSceneRequest;

typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneRequest > AddObjectToSceneRequestPtr;
typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneRequest const> AddObjectToSceneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.object_template == rhs.object_template &&
    lhs.frame_id == rhs.frame_id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb9b76adbf7ae472f5745ad9db6145d";
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb9b76adbf7ae47ULL;
  static const uint64_t static_value2 = 0x2f5745ad9db6145dULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_commander/AddObjectToSceneRequest";
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string object_template\n"
"string frame_id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.object_template);
      stream.next(m.frame_id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObjectToSceneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_commander::AddObjectToSceneRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_template: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_template);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENEREQUEST_H
