// Generated by gencpp from file moveit_commander/AddObjectToScene.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENE_H
#define MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENE_H

#include <ros/service_traits.h>


#include <moveit_commander/AddObjectToSceneRequest.h>
#include <moveit_commander/AddObjectToSceneResponse.h>


namespace moveit_commander
{

struct AddObjectToScene
{

typedef AddObjectToSceneRequest Request;
typedef AddObjectToSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddObjectToScene
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::AddObjectToScene > {
  static const char* value()
  {
    return "ef97a7771d19303a88031df9a8b7a932";
  }

  static const char* value(const ::moveit_commander::AddObjectToScene&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::AddObjectToScene > {
  static const char* value()
  {
    return "moveit_commander/AddObjectToScene";
  }

  static const char* value(const ::moveit_commander::AddObjectToScene&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::AddObjectToSceneRequest> should match
// service_traits::MD5Sum< ::moveit_commander::AddObjectToScene >
template<>
struct MD5Sum< ::moveit_commander::AddObjectToSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::AddObjectToScene >::value();
  }
  static const char* value(const ::moveit_commander::AddObjectToSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::AddObjectToSceneRequest> should match
// service_traits::DataType< ::moveit_commander::AddObjectToScene >
template<>
struct DataType< ::moveit_commander::AddObjectToSceneRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::AddObjectToScene >::value();
  }
  static const char* value(const ::moveit_commander::AddObjectToSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::AddObjectToSceneResponse> should match
// service_traits::MD5Sum< ::moveit_commander::AddObjectToScene >
template<>
struct MD5Sum< ::moveit_commander::AddObjectToSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::AddObjectToScene >::value();
  }
  static const char* value(const ::moveit_commander::AddObjectToSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::AddObjectToSceneResponse> should match
// service_traits::DataType< ::moveit_commander::AddObjectToScene >
template<>
struct DataType< ::moveit_commander::AddObjectToSceneResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::AddObjectToScene >::value();
  }
  static const char* value(const ::moveit_commander::AddObjectToSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENE_H
