// Generated by gencpp from file moveit_commander/AddObjectToSceneResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENERESPONSE_H
#define MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_commander
{
template <class ContainerAllocator>
struct AddObjectToSceneResponse_
{
  typedef AddObjectToSceneResponse_<ContainerAllocator> Type;

  AddObjectToSceneResponse_()
    : acknowledge(false)  {
    }
  AddObjectToSceneResponse_(const ContainerAllocator& _alloc)
    : acknowledge(false)  {
  (void)_alloc;
    }



   typedef uint8_t _acknowledge_type;
  _acknowledge_type acknowledge;





  typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddObjectToSceneResponse_

typedef ::moveit_commander::AddObjectToSceneResponse_<std::allocator<void> > AddObjectToSceneResponse;

typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneResponse > AddObjectToSceneResponsePtr;
typedef boost::shared_ptr< ::moveit_commander::AddObjectToSceneResponse const> AddObjectToSceneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator1> & lhs, const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.acknowledge == rhs.acknowledge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator1> & lhs, const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49e58fb292754f342bf15cc029614808";
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49e58fb292754f34ULL;
  static const uint64_t static_value2 = 0x2bf15cc029614808ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_commander/AddObjectToSceneResponse";
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool acknowledge\n"
;
  }

  static const char* value(const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acknowledge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObjectToSceneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_commander::AddObjectToSceneResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "acknowledge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acknowledge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_ADDOBJECTTOSCENERESPONSE_H
