// Generated by gencpp from file moveit_commander/AttachObjectRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECTREQUEST_H
#define MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_commander
{
template <class ContainerAllocator>
struct AttachObjectRequest_
{
  typedef AttachObjectRequest_<ContainerAllocator> Type;

  AttachObjectRequest_()
    : name()
    , frame_id()  {
    }
  AttachObjectRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AttachObjectRequest_

typedef ::moveit_commander::AttachObjectRequest_<std::allocator<void> > AttachObjectRequest;

typedef boost::shared_ptr< ::moveit_commander::AttachObjectRequest > AttachObjectRequestPtr;
typedef boost::shared_ptr< ::moveit_commander::AttachObjectRequest const> AttachObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_commander::AttachObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_commander::AttachObjectRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::AttachObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.frame_id == rhs.frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_commander::AttachObjectRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::AttachObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06f4215fb1ec5c28a0871e1187a86d71";
  }

  static const char* value(const ::moveit_commander::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06f4215fb1ec5c28ULL;
  static const uint64_t static_value2 = 0xa0871e1187a86d71ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_commander/AttachObjectRequest";
  }

  static const char* value(const ::moveit_commander::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string frame_id\n"
;
  }

  static const char* value(const ::moveit_commander::AttachObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_commander::AttachObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_commander::AttachObjectRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECTREQUEST_H
