// Generated by gencpp from file moveit_commander/AttachObject.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECT_H
#define MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECT_H

#include <ros/service_traits.h>


#include <moveit_commander/AttachObjectRequest.h>
#include <moveit_commander/AttachObjectResponse.h>


namespace moveit_commander
{

struct AttachObject
{

typedef AttachObjectRequest Request;
typedef AttachObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttachObject
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::AttachObject > {
  static const char* value()
  {
    return "3dc60b3ba98237bbd45bfef93f9da692";
  }

  static const char* value(const ::moveit_commander::AttachObject&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::AttachObject > {
  static const char* value()
  {
    return "moveit_commander/AttachObject";
  }

  static const char* value(const ::moveit_commander::AttachObject&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::AttachObjectRequest> should match
// service_traits::MD5Sum< ::moveit_commander::AttachObject >
template<>
struct MD5Sum< ::moveit_commander::AttachObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::AttachObject >::value();
  }
  static const char* value(const ::moveit_commander::AttachObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::AttachObjectRequest> should match
// service_traits::DataType< ::moveit_commander::AttachObject >
template<>
struct DataType< ::moveit_commander::AttachObjectRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::AttachObject >::value();
  }
  static const char* value(const ::moveit_commander::AttachObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::AttachObjectResponse> should match
// service_traits::MD5Sum< ::moveit_commander::AttachObject >
template<>
struct MD5Sum< ::moveit_commander::AttachObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::AttachObject >::value();
  }
  static const char* value(const ::moveit_commander::AttachObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::AttachObjectResponse> should match
// service_traits::DataType< ::moveit_commander::AttachObject >
template<>
struct DataType< ::moveit_commander::AttachObjectResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::AttachObject >::value();
  }
  static const char* value(const ::moveit_commander::AttachObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_ATTACHOBJECT_H
