// Generated by gencpp from file moveit_commander/ClearPathConstraints.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_CLEARPATHCONSTRAINTS_H
#define MOVEIT_COMMANDER_MESSAGE_CLEARPATHCONSTRAINTS_H

#include <ros/service_traits.h>


#include <moveit_commander/ClearPathConstraintsRequest.h>
#include <moveit_commander/ClearPathConstraintsResponse.h>


namespace moveit_commander
{

struct ClearPathConstraints
{

typedef ClearPathConstraintsRequest Request;
typedef ClearPathConstraintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearPathConstraints
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::ClearPathConstraints > {
  static const char* value()
  {
    return "49e58fb292754f342bf15cc029614808";
  }

  static const char* value(const ::moveit_commander::ClearPathConstraints&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::ClearPathConstraints > {
  static const char* value()
  {
    return "moveit_commander/ClearPathConstraints";
  }

  static const char* value(const ::moveit_commander::ClearPathConstraints&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::ClearPathConstraintsRequest> should match
// service_traits::MD5Sum< ::moveit_commander::ClearPathConstraints >
template<>
struct MD5Sum< ::moveit_commander::ClearPathConstraintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::ClearPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::ClearPathConstraintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::ClearPathConstraintsRequest> should match
// service_traits::DataType< ::moveit_commander::ClearPathConstraints >
template<>
struct DataType< ::moveit_commander::ClearPathConstraintsRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::ClearPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::ClearPathConstraintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::ClearPathConstraintsResponse> should match
// service_traits::MD5Sum< ::moveit_commander::ClearPathConstraints >
template<>
struct MD5Sum< ::moveit_commander::ClearPathConstraintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::ClearPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::ClearPathConstraintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::ClearPathConstraintsResponse> should match
// service_traits::DataType< ::moveit_commander::ClearPathConstraints >
template<>
struct DataType< ::moveit_commander::ClearPathConstraintsResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::ClearPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::ClearPathConstraintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_CLEARPATHCONSTRAINTS_H
