// Generated by gencpp from file moveit_commander/DetachObject.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_DETACHOBJECT_H
#define MOVEIT_COMMANDER_MESSAGE_DETACHOBJECT_H

#include <ros/service_traits.h>


#include <moveit_commander/DetachObjectRequest.h>
#include <moveit_commander/DetachObjectResponse.h>


namespace moveit_commander
{

struct DetachObject
{

typedef DetachObjectRequest Request;
typedef DetachObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetachObject
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::DetachObject > {
  static const char* value()
  {
    return "f24e999f14fde73573863e4f3aa6d481";
  }

  static const char* value(const ::moveit_commander::DetachObject&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::DetachObject > {
  static const char* value()
  {
    return "moveit_commander/DetachObject";
  }

  static const char* value(const ::moveit_commander::DetachObject&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::DetachObjectRequest> should match
// service_traits::MD5Sum< ::moveit_commander::DetachObject >
template<>
struct MD5Sum< ::moveit_commander::DetachObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::DetachObject >::value();
  }
  static const char* value(const ::moveit_commander::DetachObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::DetachObjectRequest> should match
// service_traits::DataType< ::moveit_commander::DetachObject >
template<>
struct DataType< ::moveit_commander::DetachObjectRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::DetachObject >::value();
  }
  static const char* value(const ::moveit_commander::DetachObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::DetachObjectResponse> should match
// service_traits::MD5Sum< ::moveit_commander::DetachObject >
template<>
struct MD5Sum< ::moveit_commander::DetachObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::DetachObject >::value();
  }
  static const char* value(const ::moveit_commander::DetachObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::DetachObjectResponse> should match
// service_traits::DataType< ::moveit_commander::DetachObject >
template<>
struct DataType< ::moveit_commander::DetachObjectResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::DetachObject >::value();
  }
  static const char* value(const ::moveit_commander::DetachObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_DETACHOBJECT_H
