// Generated by gencpp from file moveit_commander/ExecuteSequenceRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCEREQUEST_H
#define MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_commander
{
template <class ContainerAllocator>
struct ExecuteSequenceRequest_
{
  typedef ExecuteSequenceRequest_<ContainerAllocator> Type;

  ExecuteSequenceRequest_()
    : sequence_name()  {
    }
  ExecuteSequenceRequest_(const ContainerAllocator& _alloc)
    : sequence_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sequence_name_type;
  _sequence_name_type sequence_name;





  typedef boost::shared_ptr< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSequenceRequest_

typedef ::moveit_commander::ExecuteSequenceRequest_<std::allocator<void> > ExecuteSequenceRequest;

typedef boost::shared_ptr< ::moveit_commander::ExecuteSequenceRequest > ExecuteSequenceRequestPtr;
typedef boost::shared_ptr< ::moveit_commander::ExecuteSequenceRequest const> ExecuteSequenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sequence_name == rhs.sequence_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52c8109f5f66115d8b7c47f5e2f8a7f7";
  }

  static const char* value(const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52c8109f5f66115dULL;
  static const uint64_t static_value2 = 0x8b7c47f5e2f8a7f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_commander/ExecuteSequenceRequest";
  }

  static const char* value(const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sequence_name\n"
;
  }

  static const char* value(const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSequenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_commander::ExecuteSequenceRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sequence_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sequence_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCEREQUEST_H
