// Generated by gencpp from file moveit_commander/ExecuteSequence.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCE_H
#define MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCE_H

#include <ros/service_traits.h>


#include <moveit_commander/ExecuteSequenceRequest.h>
#include <moveit_commander/ExecuteSequenceResponse.h>


namespace moveit_commander
{

struct ExecuteSequence
{

typedef ExecuteSequenceRequest Request;
typedef ExecuteSequenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteSequence
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::ExecuteSequence > {
  static const char* value()
  {
    return "65d92ddaa3284a638f28b061d5f3a854";
  }

  static const char* value(const ::moveit_commander::ExecuteSequence&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::ExecuteSequence > {
  static const char* value()
  {
    return "moveit_commander/ExecuteSequence";
  }

  static const char* value(const ::moveit_commander::ExecuteSequence&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::ExecuteSequenceRequest> should match
// service_traits::MD5Sum< ::moveit_commander::ExecuteSequence >
template<>
struct MD5Sum< ::moveit_commander::ExecuteSequenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::ExecuteSequence >::value();
  }
  static const char* value(const ::moveit_commander::ExecuteSequenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::ExecuteSequenceRequest> should match
// service_traits::DataType< ::moveit_commander::ExecuteSequence >
template<>
struct DataType< ::moveit_commander::ExecuteSequenceRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::ExecuteSequence >::value();
  }
  static const char* value(const ::moveit_commander::ExecuteSequenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::ExecuteSequenceResponse> should match
// service_traits::MD5Sum< ::moveit_commander::ExecuteSequence >
template<>
struct MD5Sum< ::moveit_commander::ExecuteSequenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::ExecuteSequence >::value();
  }
  static const char* value(const ::moveit_commander::ExecuteSequenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::ExecuteSequenceResponse> should match
// service_traits::DataType< ::moveit_commander::ExecuteSequence >
template<>
struct DataType< ::moveit_commander::ExecuteSequenceResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::ExecuteSequence >::value();
  }
  static const char* value(const ::moveit_commander::ExecuteSequenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_EXECUTESEQUENCE_H
