// Generated by gencpp from file moveit_commander/RemoveObjectFromScene.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_REMOVEOBJECTFROMSCENE_H
#define MOVEIT_COMMANDER_MESSAGE_REMOVEOBJECTFROMSCENE_H

#include <ros/service_traits.h>


#include <moveit_commander/RemoveObjectFromSceneRequest.h>
#include <moveit_commander/RemoveObjectFromSceneResponse.h>


namespace moveit_commander
{

struct RemoveObjectFromScene
{

typedef RemoveObjectFromSceneRequest Request;
typedef RemoveObjectFromSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveObjectFromScene
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::RemoveObjectFromScene > {
  static const char* value()
  {
    return "f24e999f14fde73573863e4f3aa6d481";
  }

  static const char* value(const ::moveit_commander::RemoveObjectFromScene&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::RemoveObjectFromScene > {
  static const char* value()
  {
    return "moveit_commander/RemoveObjectFromScene";
  }

  static const char* value(const ::moveit_commander::RemoveObjectFromScene&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::RemoveObjectFromSceneRequest> should match
// service_traits::MD5Sum< ::moveit_commander::RemoveObjectFromScene >
template<>
struct MD5Sum< ::moveit_commander::RemoveObjectFromSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::RemoveObjectFromScene >::value();
  }
  static const char* value(const ::moveit_commander::RemoveObjectFromSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::RemoveObjectFromSceneRequest> should match
// service_traits::DataType< ::moveit_commander::RemoveObjectFromScene >
template<>
struct DataType< ::moveit_commander::RemoveObjectFromSceneRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::RemoveObjectFromScene >::value();
  }
  static const char* value(const ::moveit_commander::RemoveObjectFromSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::RemoveObjectFromSceneResponse> should match
// service_traits::MD5Sum< ::moveit_commander::RemoveObjectFromScene >
template<>
struct MD5Sum< ::moveit_commander::RemoveObjectFromSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::RemoveObjectFromScene >::value();
  }
  static const char* value(const ::moveit_commander::RemoveObjectFromSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::RemoveObjectFromSceneResponse> should match
// service_traits::DataType< ::moveit_commander::RemoveObjectFromScene >
template<>
struct DataType< ::moveit_commander::RemoveObjectFromSceneResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::RemoveObjectFromScene >::value();
  }
  static const char* value(const ::moveit_commander::RemoveObjectFromSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_REMOVEOBJECTFROMSCENE_H
