// Generated by gencpp from file moveit_commander/SetPathConstraints.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTS_H
#define MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTS_H

#include <ros/service_traits.h>


#include <moveit_commander/SetPathConstraintsRequest.h>
#include <moveit_commander/SetPathConstraintsResponse.h>


namespace moveit_commander
{

struct SetPathConstraints
{

typedef SetPathConstraintsRequest Request;
typedef SetPathConstraintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPathConstraints
} // namespace moveit_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_commander::SetPathConstraints > {
  static const char* value()
  {
    return "f24e999f14fde73573863e4f3aa6d481";
  }

  static const char* value(const ::moveit_commander::SetPathConstraints&) { return value(); }
};

template<>
struct DataType< ::moveit_commander::SetPathConstraints > {
  static const char* value()
  {
    return "moveit_commander/SetPathConstraints";
  }

  static const char* value(const ::moveit_commander::SetPathConstraints&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_commander::SetPathConstraintsRequest> should match
// service_traits::MD5Sum< ::moveit_commander::SetPathConstraints >
template<>
struct MD5Sum< ::moveit_commander::SetPathConstraintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::SetPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::SetPathConstraintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::SetPathConstraintsRequest> should match
// service_traits::DataType< ::moveit_commander::SetPathConstraints >
template<>
struct DataType< ::moveit_commander::SetPathConstraintsRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::SetPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::SetPathConstraintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_commander::SetPathConstraintsResponse> should match
// service_traits::MD5Sum< ::moveit_commander::SetPathConstraints >
template<>
struct MD5Sum< ::moveit_commander::SetPathConstraintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_commander::SetPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::SetPathConstraintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_commander::SetPathConstraintsResponse> should match
// service_traits::DataType< ::moveit_commander::SetPathConstraints >
template<>
struct DataType< ::moveit_commander::SetPathConstraintsResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_commander::SetPathConstraints >::value();
  }
  static const char* value(const ::moveit_commander::SetPathConstraintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTS_H
