// Generated by gencpp from file moveit_commander/SetPathConstraintsRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTSREQUEST_H
#define MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_commander
{
template <class ContainerAllocator>
struct SetPathConstraintsRequest_
{
  typedef SetPathConstraintsRequest_<ContainerAllocator> Type;

  SetPathConstraintsRequest_()
    : name()  {
    }
  SetPathConstraintsRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPathConstraintsRequest_

typedef ::moveit_commander::SetPathConstraintsRequest_<std::allocator<void> > SetPathConstraintsRequest;

typedef boost::shared_ptr< ::moveit_commander::SetPathConstraintsRequest > SetPathConstraintsRequestPtr;
typedef boost::shared_ptr< ::moveit_commander::SetPathConstraintsRequest const> SetPathConstraintsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator1> & lhs, const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_commander/SetPathConstraintsRequest";
  }

  static const char* value(const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPathConstraintsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_commander::SetPathConstraintsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_COMMANDER_MESSAGE_SETPATHCONSTRAINTSREQUEST_H
